export type Role = "Owner" | "Member" | "Viewer";

export type ThemePreference = "light" | "dark" | "system";

export type ResolvedTheme = "light" | "dark";

export interface User {
  id: string;
  email: string;
  displayName: string;
  role: Role;
  currency: string;
  themePreference: ThemePreference;
  createdAt: number;
}

/** Public-facing session user. */
export type SessionUser = User;

export type RecurringFrequency = "weekly" | "monthly" | "yearly";

export interface Category {
  id: string;
  userId: string;
  name: string;
  /** Key into the icon registry. */
  icon: string;
  /** Optional monthly budget limit. 0 / undefined means no budget. */
  monthlyBudget?: number;
  archived: boolean;
  createdAt: number;
}

export interface Expense {
  id: string;
  userId: string;
  amount: number;
  merchant: string;
  categoryId: string;
  /** ISO date string (yyyy-mm-dd). */
  date: string;
  paymentMethod?: string;
  notes?: string;
  /** Reference to a stored receipt blob, if any. */
  receiptId?: string;
  /** Set when this expense was generated by a recurring rule. */
  recurringId?: string;
  /** Period key used for idempotent recurring generation (e.g. 2026-06). */
  recurringPeriod?: string;
  /** Set when this expense was reimbursed and should stay in logs but not count toward totals. */
  excludedFromTotals?: boolean;
  /** Set on payer-side expenses created from a confirmed reimbursement. */
  reimbursementRequestId?: string;
  createdAt: number;
  updatedAt: number;
}

export interface Receipt {
  id: string;
  userId: string;
  /** Base64 data URL of the compressed image. */
  dataUrl: string;
  createdAt: number;
}

export interface Recurring {
  id: string;
  userId: string;
  amount: number;
  merchant: string;
  categoryId: string;
  frequency: RecurringFrequency;
  /** ISO date string for the next due date. */
  nextDue: string;
  paymentMethod?: string;
  notes?: string;
  createdAt: number;
}

export interface ExpenseInput {
  amount: number;
  merchant: string;
  categoryId: string;
  date: string;
  paymentMethod?: string;
  notes?: string;
  receiptId?: string;
  /** When set, creates a pending reimbursement request for the partner to pay back. */
  requestReimbursement?: {
    payerEmail: string;
    payerName: string;
    requesterName: string;
  };
  /** When true on update, removes a pending reimbursement request for this expense. */
  clearReimbursement?: boolean;
}

export type ReimbursementStatus = "pending" | "awaiting_confirmation" | "completed";

export interface ReimbursementRequest {
  id: string;
  expenseId: string;
  requesterId: string;
  requesterName: string;
  payerEmail: string;
  payerName: string;
  amount: number;
  merchant: string;
  status: ReimbursementStatus;
  createdAt: number;
  completedAt?: number;
  /** Expense id on the payer's account after confirmation. */
  payerExpenseId?: string;
}

/** Monthly income entry — multiple rows per month are summed on the dashboard. */
export interface IncomeEntry {
  id: string;
  userId: string;
  amount: number;
  /** Month bucket yyyy-mm. */
  month: string;
  label?: string;
  createdAt: number;
}

export interface IncomeInput {
  amount: number;
  month: string;
  label?: string;
}
