export type Role = "Owner" | "Member" | "Viewer";

export type ThemePreference = "light" | "dark" | "system";

export type ResolvedTheme = "light" | "dark";

export type Gender = "male" | "female";

export interface User {
  id: string;
  email: string;
  displayName: string;
  role: Role;
  currency: string;
  themePreference: ThemePreference;
  gender?: Gender;
  /** UPI VPA for Settle Up (own ID). */
  upiId?: string;
  phone?: string;
  createdAt: number;
}

/** Public-facing session user. */
export type SessionUser = User;

export type RecurringFrequency = "weekly" | "monthly" | "yearly";

export interface Category {
  id: string;
  userId: string;
  name: string;
  /** Key into the icon registry. */
  icon: string;
  /** Optional monthly budget limit. 0 / undefined means no budget. */
  monthlyBudget?: number;
  archived: boolean;
  createdAt: number;
}

export interface Expense {
  id: string;
  userId: string;
  amount: number;
  merchant: string;
  categoryId: string;
  /** ISO date string (yyyy-mm-dd). */
  date: string;
  paymentMethod?: string;
  notes?: string;
  /** Normalized tags without `#` (e.g. `trip`, `rent`). */
  tags?: string[];
  /** Reference to a stored receipt blob, if any. */
  receiptId?: string;
  /** Set when this expense was generated by a recurring rule. */
  recurringId?: string;
  /** Period key used for idempotent recurring generation (e.g. 2026-06). */
  recurringPeriod?: string;
  /** Set when this expense was reimbursed and should stay in logs but not count toward totals. */
  excludedFromTotals?: boolean;
  /** Set on payer-side expenses created from a confirmed reimbursement. */
  reimbursementRequestId?: string;
  createdAt: number;
  updatedAt: number;
}

export interface Receipt {
  id: string;
  userId: string;
  /** Base64 data URL of the compressed image. */
  dataUrl: string;
  createdAt: number;
}

export interface Recurring {
  id: string;
  userId: string;
  amount: number;
  merchant: string;
  categoryId: string;
  frequency: RecurringFrequency;
  /** ISO date string for the next due date. */
  nextDue: string;
  paymentMethod?: string;
  notes?: string;
  createdAt: number;
}

export interface ExpenseInput {
  amount: number;
  merchant: string;
  categoryId: string;
  date: string;
  paymentMethod?: string;
  notes?: string;
  /** Normalized tags without `#`. */
  tags?: string[];
  receiptId?: string;
  /** Set when logging from a recurring rule (idempotency). */
  recurringId?: string;
  recurringPeriod?: string;
  /** When set, creates a pending reimbursement request for the partner to pay back. */
  requestReimbursement?: {
    payerEmail: string;
    payerName: string;
    requesterName: string;
    /**
     * Amount the partner owes. Defaults to the full expense amount.
     * Use a lower value for splits (e.g. 50% of the bill you paid).
     */
    amount?: number;
  };
  /** When true on update, removes a pending reimbursement request for this expense. */
  clearReimbursement?: boolean;
}

export type ReimbursementStatus = "pending" | "awaiting_confirmation" | "completed";

export interface ReimbursementRequest {
  id: string;
  expenseId: string;
  requesterId: string;
  requesterName: string;
  payerEmail: string;
  payerName: string;
  amount: number;
  merchant: string;
  status: ReimbursementStatus;
  createdAt: number;
  completedAt?: number;
  /** Expense id on the payer's account after confirmation. */
  payerExpenseId?: string;
}

export type SettlementMethod = "upi" | "cash" | "other";
export type SettlementStatus = "initiated" | "payer_confirmed" | "cancelled";

export interface Settlement {
  id: string;
  reimbursementRequestId: string;
  payerId: string;
  payeeId: string;
  amount: number;
  method: SettlementMethod;
  note?: string;
  status: SettlementStatus;
  createdAt: number;
  settledAt?: number;
  /** Denormalized for UI when joined. */
  payerName?: string;
  payeeName?: string;
  merchant?: string;
}

/** Monthly income entry — multiple rows per month are summed on the dashboard. */
export interface IncomeEntry {
  id: string;
  userId: string;
  amount: number;
  /** Month bucket yyyy-mm. */
  month: string;
  label?: string;
  createdAt: number;
}

export interface IncomeInput {
  amount: number;
  month: string;
  label?: string;
}
