export type Role = "Owner" | "Member" | "Viewer";

export type ThemePreference = "light" | "dark" | "system";

export type ResolvedTheme = "light" | "dark";

export interface User {
  id: string;
  email: string;
  /** Passcode hash (local-only auth, not real security). */
  passHash: string;
  displayName: string;
  role: Role;
  currency: string;
  themePreference: ThemePreference;
  createdAt: number;
}

/** Public-facing session user (no secrets). */
export type SessionUser = Omit<User, "passHash">;

export type RecurringFrequency = "weekly" | "monthly" | "yearly";

export interface Category {
  id: string;
  userId: string;
  name: string;
  /** Key into the icon registry. */
  icon: string;
  /** Optional monthly budget limit. 0 / undefined means no budget. */
  monthlyBudget?: number;
  archived: boolean;
  createdAt: number;
}

export interface Expense {
  id: string;
  userId: string;
  amount: number;
  merchant: string;
  categoryId: string;
  /** ISO date string (yyyy-mm-dd). */
  date: string;
  paymentMethod?: string;
  notes?: string;
  /** Reference to a stored receipt blob, if any. */
  receiptId?: string;
  /** Set when this expense was generated by a recurring rule. */
  recurringId?: string;
  /** Period key used for idempotent recurring generation (e.g. 2026-06). */
  recurringPeriod?: string;
  createdAt: number;
  updatedAt: number;
}

export interface Receipt {
  id: string;
  userId: string;
  /** Base64 data URL of the compressed image. */
  dataUrl: string;
  createdAt: number;
}

export interface Recurring {
  id: string;
  userId: string;
  amount: number;
  merchant: string;
  categoryId: string;
  frequency: RecurringFrequency;
  /** ISO date string for the next due date. */
  nextDue: string;
  paymentMethod?: string;
  notes?: string;
  createdAt: number;
}

export interface ExpenseInput {
  amount: number;
  merchant: string;
  categoryId: string;
  date: string;
  paymentMethod?: string;
  notes?: string;
  receiptId?: string;
}
